version: "3.8"

services:
  wb-advert:
    build: .
    restart: always
    container_name: wb-advert
    environment:
      TZ: Europe/Moscow
#      ECOMRU_PG_DB_NAME: ${ECOMRU_PG_DB_NAME}
#      ECOMRU_PG_HOST: ${ECOMRU_PG_HOST}
#      ECOMRU_PG_PORT: ${ECOMRU_PG_PORT}
#      ECOMRU_PG_USER: ${ECOMRU_PG_USER}
#      ECOMRU_PG_PASSWORD: ${ECOMRU_PG_PASSWORD}
#      ECOMRU_PG_SSL_MODE: ${ECOMRU_PG_SSL_MODE}
    volumes:
      - /home/get/logs_all//wb_advert/:/app/logs/

  nginx:
    container_name: nginx-wb-advert
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - wb-advert
    restart: always
    environment:
      - "TZ=Europe/Moscow"
    ports:
      - 8096:80
      - 4450:443
    volumes:
      - /home/get/cert:/app/cert

