swagger: "2.0"
info:
  title: "Wildberries advert Ecom API documentation"
  contact:
    email: "s.fedyushin@gtcom.io"
  basePath: "/swagger"
paths:
  "/wbadvert/campaignpause":
    post:
tags:
  - campaigns
summary: "Поставить кампанию на паузу"
description: "Метод для постановки рекламной кампании на паузу"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "body"
  name: "body"
  required: true
  schema:
    type: "object"
    properties:
      api_key:
        type: "string"
        example: "xYcUsddPPsadwdwqdlKJHbgCF"
        description: ключ API
      campaign_id:
        type: "integer"
        example: 1234
        description: Идентификатор РК
responses:
  200:
    description: "OK"
  400:
    description: "Bad Request"