swagger: "2.0"
info:
  title: "Wildberries advert Ecom API documentation"
  contact:
    email: "s.fedyushin@gtcom.io"
  basePath: "/swagger"
paths:
  "/wbfeedbacks/productsrating":
    post:
tags:
  - feedbacks
summary: "Средняя оценка товаров по родительской категории"
description: "Метод позволяет получить среднюю оценку товаров по родительской категории."
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "body"
  name: "body"
  required: true
  schema:
    type: "object"
    properties:
      api_key:
        type: "string"
        example: "xYcUsddPPsadwdwqdlKJHbgCF"
        description: ключ API
      subject_id:
        type: "integer"
        example: 3109
        description: id категории товара
responses:
  200:
    description: "OK"
  400:
    description: "Bad Request"