swagger: "2.0"
info:
  title: "Wildberries advert Ecom API documentation"
  contact:
    email: "s.fedyushin@gtcom.io"
  basePath: "/swagger"
paths:
  "/wbfeedbacks/productsratingnmid":
    post:
tags:
  - feedbacks
summary: "Средняя оценка товара по nmId"
description: "Метод позволяет получить среднюю оценку товара по его nmId"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "body"
  name: "body"
  required: true
  schema:
    type: "object"
    properties:
      api_key:
        type: "string"
        example: "xYcUsddPPsadwdwqdlKJHbgCF"
        description: ключ API
      nm_id:
        type: "integer"
        example: 5870243
        description: Числовой идентификатор номенклатуры Wildberries
responses:
  200:
    description: "OK"
  400:
    description: "Bad Request"