swagger: "2.0"
info:
  title: "Wildberries advert Ecom API documentation"
  contact:
    email: "s.fedyushin@gtcom.io"
  basePath: "/swagger"
paths:
  "/wbadvert/nmactiveedit":
    post:
tags:
  - campaigns
summary: "Изменение активности номенклатур кампании"
description: "Метод для изменения активности номенклатур кампании"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "body"
  name: "body"
  required: true
  schema:
    type: "object"
    properties:
      api_key:
        type: "string"
        example: "xYcUsddPPsadwdwqdlKJHbgCF"
        description: ключ API
      advert_id:
        type: "integer"
        example: 1234
        description: Идентификатор РК
      active_nm:
        type:
          - array
            - integer
        example: [2116745, 2116746]
        description: Числовые идентификаторы номенклатуры Wildberries (nmId)
      active_states:
        type:
          - array
            - string
        example: ["true", "false"]
        description: Новое состояние (true - сделать номенклатуру активной или false - сделать номенклатуру неактивной)
        enum:
          - "true"
          - "false"
      param:
        type: "integer"
        example: 275
        description: Параметр, для которого будет внесено изменение, должен быть значением menuId (для РК в каталоге), subjectId (для РК в поиске и рекомендациях) или setId (для РК в карточке товара)
responses:
  200:
    description: "OK"
  400:
    description: "Bad Request"

