swagger: "2.0"
info:
  title: "Wildberries advert Ecom API documentation"
  contact:
    email: "s.fedyushin@gtcom.io"
  basePath: "/swagger"
paths:
  "/wbquestions/unanswered":
    post:
tags:
  - questions
summary: "Неотвеченные вопросы"
description: "Метод позволяет получить количество неотвеченных вопросов за сегодня и за всё время."
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "body"
  name: "body"
  required: true
  schema:
    type: "object"
    properties:
      api_key:
        type: "string"
        example: "xYcUsddPPsadwdwqdlKJHbgCF"
        description: ключ API
responses:
  200:
    description: "OK"
  400:
    description: "Bad Request"

